version: '3.8'

services:
  postgres:
    image: 'postgres:13.4'
    volumes:
      - data:/data/db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: twitter-clone
    env_file:
      - ./backend/production.env
    container_name: postgres-db
  backend:
    build: ./backend/
    ports:
      - '4000:4000'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/production.env
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - data:/data/redis
    restart: always

volumes:
  data:
  logs:
